### ISSUE TITLE
Reading a '.sbfmf' file

### ISSUE THREAD

**Issue by thatcher** [motmot/flymovieformat#1]
I'm trying to read a file from http://ctrax.sourceforge.net/ctrax.html#example-video-annotation-and-mat-files specifically movie20071009_163231.sbfmf from http://sourceforge.net/projects/ctrax/files/Ctrax%20samples/example-sbfmfvideo-ann-mat-5M5F5min-20090518.zip/download

I can't find any documentation on the .sbfmf format versus the .fmf format so I'm guessing that difference is the cause of my issue.  Here is the gist of how Im trying to convert the fmf to an mp4 (on mac osx 10.5) using opencv.

``` python
import cv2
import motmot.FlyMovieFormat.FlyMovieFormat as FlyMovieFormat

capture_stream = FlyMovieFormat.FlyMovie('video/movie20071009_163231.sbfmf')

# define the codec and create VideoWriter object
codec = cv2.cv.CV_FOURCC('m','p','4','v')
size = (capture_stream.get_width(), capture_stream.get_height())
frames_per_second = 20
output_stream = cv2.VideoWriter(
    'video/five_flys.mp4',
    codec,
    frames_per_second, # Frames per second
    size # Width / Height
)

for frame_number in range(capture_stream.get_n_frames()):
    frame,timestamp = capture_stream.get_frame(frame_number)

    try:
        output_stream.write(frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    except Exception,e:
        print e
        break


capture_stream.release()
output_stream.release()
```

And I get a big stack trace:

```
$ python fmf2mp4.py 
(0, 4215296)
Traceback (most recent call last):
  File "fmf2mp4.py", line 26, in <module>
    frame,timestamp = capture_stream.get_frame(frame_number)
  File "build/bdist.macosx-10.5-x86_64/egg/motmot/FlyMovieFormat/FlyMovieFormat.py", line 332, in get_frame
  File "build/bdist.macosx-10.5-x86_64/egg/motmot/FlyMovieFormat/FlyMovieFormat.py", line 327, in get_next_frame
  File "build/bdist.macosx-10.5-x86_64/egg/motmot/FlyMovieFormat/FlyMovieFormat.py", line 293, in _read_next_frame
NotImplementedError: Reading not implemented for |??N?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o@?o...
```

No rush, just playing.  Thanks.

Thatcher

**Comment by astraw** [comment]
Oh, sorry, I missed this issue when you filed it 5 years ago. I don't know much about sbfmf files and certainly would not expect them to be compatible with fmf. I'm closing the issue. Sorry once again for the delay.
